### ISSUE TITLE
Add contributing instructions

### ISSUE THREAD

**Issue by jakerella** [strongloop-training/coffee-time#1]
We need to add info on how to add/fix things in this repo now that the tags are set. In other words, if something needs to change in step 3, how do we do that and still have the step 3 tag work? And does that change filter down to the other steps or do we have to re-tag the entire repo?

**Comment by Sequoia** [comment]
https://github.com/Sequoia/coffee-time/blob/wip-before-retagging/CONTRIBUTING.md
:warning: not retagged/on master yet

**Comment by Sequoia** [comment]
[merged](https://github.com/strongloop-training/coffee-time/blob/master/CONTRIBUTING.md)
