### ISSUE TITLE
Missing middleware example

### ISSUE THREAD

**Issue by jakerella** [strongloop-training/coffee-time#2]
At some point we had an example of using middleware with the coffee review app. We need to add that back in (or just create a new example). I think the old one was just a simple request logger (to the console).

**Comment by Sequoia** [comment]
10-4. Will look into this and add the instructions for retagging tomorrow

**Comment by Sequoia** [comment]
# plan
1. create custom "logging" middleware (log requests to console)
2. load this via middleware.json

Is that sufficient or do you have something else in mind?

**Comment by jakerella** [comment]
Yep. Let's make the logger just spit out the URL of the request, I'm thinking in the `initial` or `auth` phase.

**Comment by Sequoia** [comment]
I'll add it after ACL step as it was in the previous coffee-time https://github.com/jakerella/coffee-time/commit/7c1867824bc8aab11c90b8ec031e2bc6492ab24b

**Comment by Sequoia** [comment]
https://github.com/Sequoia/coffee-time/commit/929e80de49bc816bfc1793d76bdb943f40d07de7

Copied from old version with the one change: used `./middleware/logger` path per [these docs](https://docs.strongloop.com/display/public/LB/Defining+middleware#Definingmiddleware-Pathtomiddlewarefunction)

:warning: not retagged/pushed to master yet

**Comment by Sequoia** [comment]
[merged](https://github.com/strongloop-training/coffee-time/commit/929e80de49bc816bfc1793d76bdb943f40d07de7)
