### ISSUE TITLE
Missing async dependency

### ISSUE THREAD

**Issue by jakerella** [strongloop-training/coffee-time#5]
It looks like the `async` library is used in the data sample generator but not in `package.json`.

**Comment by Sequoia** [comment]
addressed [here](https://github.com/Sequoia/coffee-time/commit/db341dadb9916f7141ebed1c414c7c5608aa4cbb#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R10)
:warning: not retagged/on master yet

**Comment by Sequoia** [comment]
[merged](https://github.com/strongloop-training/coffee-time/commit/db341dadb9916f7141ebed1c414c7c5608aa4cbb#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R10)
